### ISSUE TITLE
Checkboxes not responding when adding funds

### ISSUE THREAD

**Issue by nixolas1** [dotKom/nibble#1]
The clicked checkbox's value is not stored in the model.

**Comment by nornes** [comment]
I think it's because both the checkboxes and the custom amount uses the add_money_amount model, so its always set to the custom amount because that comes last in the code. Maybe we should use different models? 

Also the checkboxes should be un-checked when a custom amount is added and the custom amount set to 0 when checkboxes are clicked. 

Edit: The problem lays in the ng-repeat which creates a child scope for each amount and only changes the value in the separate scope. This article describes it good, though I haven't figured out the solution yet: http://www.codelord.net/2014/05/10/understanding-angulars-magic-dont-bind-to-primitives/
